openapi: 3.0.1
info:
  title: OpenQQuantify Plugin
  description: Recommend devices, compare features, summarize products, and delegate tasks to specialized AI agents for tutoring, resume help, and startup advice.
  version: '1.0'
servers:
  - url: http://localhost:5000 # Remember to change this to your deployed domain
paths:
  /recommend:
    post:
      summary: Recommend tech products based on budget, use case, and preferred specifications.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                budget:
                  type: number
                  description: The maximum budget for the product.
                use_case:
                  type: string
                  description: The primary use case for the product (e.g., "robotics", "iot", "ai", "gaming", "learning").
                preferred_specs:
                  type: object
                  description: Optional specific technical specifications desired (e.g., {"ram": "8GB", "storage": "256GB"}).
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: A list of recommended products matching the criteria.
          content:
            application/json:
              schema:
                type: object
                properties:
                  recommendations:
                    type: array
                    items:
                      type: object # Define a product schema if possible for better docs

  /compare:
    post:
      summary: Compare multiple tech products by their IDs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_ids:
                  type: array
                  items:
                    type: string
                  description: An array of product IDs to compare.
      responses:
        '200':
          description: A comparison of the selected products.
          content:
            application/json:
              schema:
                type: object
                properties:
                  comparison:
                    type: array
                    items:
                      type: object # Define a product schema if possible

  /summarize:
    post:
      summary: Generate a GPT-powered summary and comparison of selected products.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_ids:
                  type: array
                  items:
                    type: string
                  description: An array of product IDs to summarize.
      responses:
        '200':
          description: A summary and comparison generated by the AI.
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string

  /delegate:
    post:
      summary: Delegate a task to a specialized AI agent (e.g., tutoring, resume, startup).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent:
                  type: string
                  description: The name of the agent to delegate to (e.g., "tutoring", "resume", "startup").
                task:
                  type: string
                  description: The specific task or query for the agent.
                parameters:
                  type: object
                  description: Additional parameters specific to the agent's task.
                  additionalProperties: true
      responses:
        '200':
          description: The response from the delegated AI agent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: object 